### PR TITLE
Pass env to `slugify`

### PR DESCRIPTION
**Pull request by Kaciras**
Make it possible to prefix slugs differently in each render

### CODE REVIEW

**Comment by shynome** [comment]
want this too

**Comment by valeriangalliat** [comment]
I was thinking of passing the whole `state` param instead so this gives access to not only `env` but any other thing interesting in there... not sure if that makes sense

What do you use from `state.env` that you want to access from the slugify function?

**Comment by shynome** [comment]
want add prefix `post.id`

**Comment by valeriangalliat** [comment]
Cool, sorry for the delay - I just refactored this to pass the whole `state` instead of just `env`, so you can do `state.env`, and I put it in an alternative option `slugifyWithState` to avoid a possible breaking change with `slugify`

It's live with 9.1.01

**Pull request merged**
